commit deploy yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -58,16 +58,24 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
             terraform apply -auto-approve
-            terraform output -raw ec2_public_ip > ec2_ip.txt
-            terraform output -raw rds_endpoint > rds_endpoint.txt
+            terraform output -raw ec2_public_ip > $GITHUB_WORKSPACE/ec2_ip.txt
+            terraform output -raw rds_endpoint > $GITHUB_WORKSPACE/rds_endpoint.txt
 
       # 8. Export the RDS endpoint as an environment variable
       - name: Set RDS Endpoint
         run: echo "RDS_ENDPOINT=$(cat rds_endpoint.txt)" >> $GITHUB_ENV
 
+      - name: Verify ec2_ip.txt
+        run: |
+            if [ ! -f $GITHUB_WORKSPACE/ec2_ip.txt ]; then
+              echo "Error: ec2_ip.txt not found!"
+              exit 1
+            fi
+            cat $GITHUB_WORKSPACE/ec2_ip.txt
+
       # 9. Transfer RDS Endpoint to EC2
       - name: Transfer RDS Endpoint to EC2
         run: |
-            EC2_IP=$(cat ec2_ip.txt)
-            scp -o StrictHostKeyChecking=no -i ./terraform/nginx-server.key rds_endpoint.txt ec2-user@$(cat ec2_ip.txt):/etc/rds_endpoint
+            EC2_IP=$(cat $GITHUB_WORKSPACE/ec2_ip.txt)
+            scp -o StrictHostKeyChecking=no -i ./terraform/nginx-server.key $GITHUB_WORKSPACE/rds_endpoint.txt ec2-user@$EC2_IP:/etc/rds_endpoint
 
